sudo: false
services:
- docker

cache:
  directories:
  - $HOME/.cache"

dist: bionic
language: java
jdk: openjdk12
deploy:
        provider: script
        script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -Drevision=$BUILD_NUMBER deploy"
        skip_cleanup: true
