sudo: false

cache:
  directories:
  - $HOME/.m2

dist: bionic
language: java
jdk: openjdk12
install: skip
script: bash script.sh || travis_terminate 0
deploy:
        provider: script
        script: "mvn -B -s settings.xml release:prepare release:perform -Dusername=garyluu -Dpassword=${GH_TOKEN}"
        skip_cleanup: true

