sudo: false
services:
- docker

cache:
  directories:
  - $HOME/.cache"

dist: bionic
language: java
jdk: openjdk12
deploy:
        provider: script
        script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -B release:prepare && mvn release:perform -Darguments=\"-Dmaven.javadoc.skip=true\""
        skip_cleanup: true
